/*
 * Source code generated by uk.ac.leeds.ccg.data.stats19.process.STATS19_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.data.stats19.data.accident;

import uk.ac.leeds.ccg.data.Data_Record;
import uk.ac.leeds.ccg.data.stats19.data.id.STATS19_RecordID;
import java.math.BigDecimal;

public class STATS19_ACCIDENT_Record extends Data_Record {

    private static final long serialVersionUID = 1L;

    protected String tAccident_Index;
    protected Integer tLocation_Easting_OSGR;
    protected Integer tLocation_Northing_OSGR;
    protected BigDecimal tLongitude;
    protected BigDecimal tLatitude;
    protected Byte tPolice_Force;
    protected Byte tAccident_Severity;
    protected Byte tNumber_of_Vehicles;
    protected Byte tNumber_of_Casualties;
    protected String tDate;
    protected Byte tDay_of_Week;
    protected String tTime;
    protected Short tLocal_Authority_District;
    protected String tLocal_Authority_Highway;
    protected Byte t1st_Road_Class;
    protected Short t1st_Road_Number;
    protected Byte tRoad_Type;
    protected Byte tSpeed_limit;
    protected Byte tJunction_Detail;
    protected Byte tJunction_Control;
    protected Byte t2nd_Road_Class;
    protected Short t2nd_Road_Number;
    protected Byte tPedestrian_Crossing_Human_Control;
    protected Byte tPedestrian_Crossing_Physical_Facilities;
    protected Byte tLight_Conditions;
    protected Byte tWeather_Conditions;
    protected Byte tRoad_Surface_Conditions;
    protected Byte tSpecial_Conditions_at_Site;
    protected Byte tCarriageway_Hazards;
    protected Byte tUrban_or_Rural_Area;
    protected Byte tDid_Police_Officer_Attend_Scene_of_Accident;
    protected String tLSOA_of_Accident_Location;

    public STATS19_ACCIDENT_Record(STATS19_RecordID i, String line) throws Exception {
        super(i);
        String[] s = line.split(",");
        inittAccident_Index(s[0]);
        inittLocation_Easting_OSGR(s[1]);
        inittLocation_Northing_OSGR(s[2]);
        inittLongitude(s[3]);
        inittLatitude(s[4]);
        inittPolice_Force(s[5]);
        inittAccident_Severity(s[6]);
        inittNumber_of_Vehicles(s[7]);
        inittNumber_of_Casualties(s[8]);
        inittDate(s[9]);
        inittDay_of_Week(s[10]);
        inittTime(s[11]);
        inittLocal_Authority_District(s[12]);
        inittLocal_Authority_Highway(s[13]);
        initt1st_Road_Class(s[14]);
        initt1st_Road_Number(s[15]);
        inittRoad_Type(s[16]);
        inittSpeed_limit(s[17]);
        inittJunction_Detail(s[18]);
        inittJunction_Control(s[19]);
        initt2nd_Road_Class(s[20]);
        initt2nd_Road_Number(s[21]);
        inittPedestrian_Crossing_Human_Control(s[22]);
        inittPedestrian_Crossing_Physical_Facilities(s[23]);
        inittLight_Conditions(s[24]);
        inittWeather_Conditions(s[25]);
        inittRoad_Surface_Conditions(s[26]);
        inittSpecial_Conditions_at_Site(s[27]);
        inittCarriageway_Hazards(s[28]);
        inittUrban_or_Rural_Area(s[29]);
        inittDid_Police_Officer_Attend_Scene_of_Accident(s[30]);
        inittLSOA_of_Accident_Location(s[31]);
    }

    @Override
    public STATS19_RecordID getID() {
        return (STATS19_RecordID) id;
    }

    protected final void inittAccident_Index(String s) {
        if (!s.trim().isEmpty()) {
            tAccident_Index = s;
        } else {
            tAccident_Index = null;
        }
    }

    protected final void inittLocation_Easting_OSGR(String s) {
        if (!s.trim().isEmpty()) {
            tLocation_Easting_OSGR = Integer.parseInt(s);
        } else {
            tLocation_Easting_OSGR = null;
        }
    }

    protected final void inittLocation_Northing_OSGR(String s) {
        if (!s.trim().isEmpty()) {
            tLocation_Northing_OSGR = Integer.parseInt(s);
        } else {
            tLocation_Northing_OSGR = null;
        }
    }

    protected final void inittLongitude(String s) {
        if (!s.trim().isEmpty()) {
            tLongitude = new BigDecimal(s);
        } else {
            tLongitude = null;
        }
    }

    protected final void inittLatitude(String s) {
        if (!s.trim().isEmpty()) {
            tLatitude = new BigDecimal(s);
        } else {
            tLatitude = null;
        }
    }

    protected final void inittPolice_Force(String s) {
        if (!s.trim().isEmpty()) {
            tPolice_Force = Byte.parseByte(s);
        } else {
            tPolice_Force = null;
        }
    }

    protected final void inittAccident_Severity(String s) {
        if (!s.trim().isEmpty()) {
            tAccident_Severity = Byte.parseByte(s);
        } else {
            tAccident_Severity = null;
        }
    }

    protected final void inittNumber_of_Vehicles(String s) {
        if (!s.trim().isEmpty()) {
            tNumber_of_Vehicles = Byte.parseByte(s);
        } else {
            tNumber_of_Vehicles = null;
        }
    }

    protected final void inittNumber_of_Casualties(String s) {
        if (!s.trim().isEmpty()) {
            tNumber_of_Casualties = Byte.parseByte(s);
        } else {
            tNumber_of_Casualties = null;
        }
    }

    protected final void inittDate(String s) {
        if (!s.trim().isEmpty()) {
            tDate = s;
        } else {
            tDate = null;
        }
    }

    protected final void inittDay_of_Week(String s) {
        if (!s.trim().isEmpty()) {
            tDay_of_Week = Byte.parseByte(s);
        } else {
            tDay_of_Week = null;
        }
    }

    protected final void inittTime(String s) {
        if (!s.trim().isEmpty()) {
            tTime = s;
        } else {
            tTime = null;
        }
    }

    protected final void inittLocal_Authority_District(String s) {
        if (!s.trim().isEmpty()) {
            tLocal_Authority_District = Short.parseShort(s);
        } else {
            tLocal_Authority_District = null;
        }
    }

    protected final void inittLocal_Authority_Highway(String s) {
        if (!s.trim().isEmpty()) {
            tLocal_Authority_Highway = s;
        } else {
            tLocal_Authority_Highway = null;
        }
    }

    protected final void initt1st_Road_Class(String s) {
        if (!s.trim().isEmpty()) {
            t1st_Road_Class = Byte.parseByte(s);
        } else {
            t1st_Road_Class = null;
        }
    }

    protected final void initt1st_Road_Number(String s) {
        if (!s.trim().isEmpty()) {
            t1st_Road_Number = Short.parseShort(s);
        } else {
            t1st_Road_Number = null;
        }
    }

    protected final void inittRoad_Type(String s) {
        if (!s.trim().isEmpty()) {
            tRoad_Type = Byte.parseByte(s);
        } else {
            tRoad_Type = null;
        }
    }

    protected final void inittSpeed_limit(String s) {
        if (!s.trim().isEmpty()) {
            tSpeed_limit = Byte.parseByte(s);
        } else {
            tSpeed_limit = null;
        }
    }

    protected final void inittJunction_Detail(String s) {
        if (!s.trim().isEmpty()) {
            tJunction_Detail = Byte.parseByte(s);
        } else {
            tJunction_Detail = null;
        }
    }

    protected final void inittJunction_Control(String s) {
        if (!s.trim().isEmpty()) {
            tJunction_Control = Byte.parseByte(s);
        } else {
            tJunction_Control = null;
        }
    }

    protected final void initt2nd_Road_Class(String s) {
        if (!s.trim().isEmpty()) {
            t2nd_Road_Class = Byte.parseByte(s);
        } else {
            t2nd_Road_Class = null;
        }
    }

    protected final void initt2nd_Road_Number(String s) {
        if (!s.trim().isEmpty()) {
            t2nd_Road_Number = Short.parseShort(s);
        } else {
            t2nd_Road_Number = null;
        }
    }

    protected final void inittPedestrian_Crossing_Human_Control(String s) {
        if (!s.trim().isEmpty()) {
            tPedestrian_Crossing_Human_Control = Byte.parseByte(s);
        } else {
            tPedestrian_Crossing_Human_Control = null;
        }
    }

    protected final void inittPedestrian_Crossing_Physical_Facilities(String s) {
        if (!s.trim().isEmpty()) {
            tPedestrian_Crossing_Physical_Facilities = Byte.parseByte(s);
        } else {
            tPedestrian_Crossing_Physical_Facilities = null;
        }
    }

    protected final void inittLight_Conditions(String s) {
        if (!s.trim().isEmpty()) {
            tLight_Conditions = Byte.parseByte(s);
        } else {
            tLight_Conditions = null;
        }
    }

    protected final void inittWeather_Conditions(String s) {
        if (!s.trim().isEmpty()) {
            tWeather_Conditions = Byte.parseByte(s);
        } else {
            tWeather_Conditions = null;
        }
    }

    protected final void inittRoad_Surface_Conditions(String s) {
        if (!s.trim().isEmpty()) {
            tRoad_Surface_Conditions = Byte.parseByte(s);
        } else {
            tRoad_Surface_Conditions = null;
        }
    }

    protected final void inittSpecial_Conditions_at_Site(String s) {
        if (!s.trim().isEmpty()) {
            tSpecial_Conditions_at_Site = Byte.parseByte(s);
        } else {
            tSpecial_Conditions_at_Site = null;
        }
    }

    protected final void inittCarriageway_Hazards(String s) {
        if (!s.trim().isEmpty()) {
            tCarriageway_Hazards = Byte.parseByte(s);
        } else {
            tCarriageway_Hazards = null;
        }
    }

    protected final void inittUrban_or_Rural_Area(String s) {
        if (!s.trim().isEmpty()) {
            tUrban_or_Rural_Area = Byte.parseByte(s);
        } else {
            tUrban_or_Rural_Area = null;
        }
    }

    protected final void inittDid_Police_Officer_Attend_Scene_of_Accident(String s) {
        if (!s.trim().isEmpty()) {
            tDid_Police_Officer_Attend_Scene_of_Accident = Byte.parseByte(s);
        } else {
            tDid_Police_Officer_Attend_Scene_of_Accident = null;
        }
    }

    protected final void inittLSOA_of_Accident_Location(String s) {
        if (!s.trim().isEmpty()) {
            tLSOA_of_Accident_Location = s;
        } else {
            tLSOA_of_Accident_Location = null;
        }
    }

    public String gettAccident_Index() {
        return tAccident_Index;
    }

    public Integer gettLocation_Easting_OSGR() {
        return tLocation_Easting_OSGR;
    }

    public Integer gettLocation_Northing_OSGR() {
        return tLocation_Northing_OSGR;
    }

    public BigDecimal gettLongitude() {
        return tLongitude;
    }

    public BigDecimal gettLatitude() {
        return tLatitude;
    }

    public Byte gettPolice_Force() {
        return tPolice_Force;
    }

    public Byte gettAccident_Severity() {
        return tAccident_Severity;
    }

    public Byte gettNumber_of_Vehicles() {
        return tNumber_of_Vehicles;
    }

    public Byte gettNumber_of_Casualties() {
        return tNumber_of_Casualties;
    }

    public String gettDate() {
        return tDate;
    }

    public Byte gettDay_of_Week() {
        return tDay_of_Week;
    }

    public String gettTime() {
        return tTime;
    }

    public Short gettLocal_Authority_District() {
        return tLocal_Authority_District;
    }

    public String gettLocal_Authority_Highway() {
        return tLocal_Authority_Highway;
    }

    public Byte gett1st_Road_Class() {
        return t1st_Road_Class;
    }

    public Short gett1st_Road_Number() {
        return t1st_Road_Number;
    }

    public Byte gettRoad_Type() {
        return tRoad_Type;
    }

    public Byte gettSpeed_limit() {
        return tSpeed_limit;
    }

    public Byte gettJunction_Detail() {
        return tJunction_Detail;
    }

    public Byte gettJunction_Control() {
        return tJunction_Control;
    }

    public Byte gett2nd_Road_Class() {
        return t2nd_Road_Class;
    }

    public Short gett2nd_Road_Number() {
        return t2nd_Road_Number;
    }

    public Byte gettPedestrian_Crossing_Human_Control() {
        return tPedestrian_Crossing_Human_Control;
    }

    public Byte gettPedestrian_Crossing_Physical_Facilities() {
        return tPedestrian_Crossing_Physical_Facilities;
    }

    public Byte gettLight_Conditions() {
        return tLight_Conditions;
    }

    public Byte gettWeather_Conditions() {
        return tWeather_Conditions;
    }

    public Byte gettRoad_Surface_Conditions() {
        return tRoad_Surface_Conditions;
    }

    public Byte gettSpecial_Conditions_at_Site() {
        return tSpecial_Conditions_at_Site;
    }

    public Byte gettCarriageway_Hazards() {
        return tCarriageway_Hazards;
    }

    public Byte gettUrban_or_Rural_Area() {
        return tUrban_or_Rural_Area;
    }

    public Byte gettDid_Police_Officer_Attend_Scene_of_Accident() {
        return tDid_Police_Officer_Attend_Scene_of_Accident;
    }

    public String gettLSOA_of_Accident_Location() {
        return tLSOA_of_Accident_Location;
    }
}
