/*
 * Source code generated by uk.ac.leeds.ccg.data.stats19.process.STATS19_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.data.stats19.data.casualty;

import uk.ac.leeds.ccg.data.Data_Record;
import uk.ac.leeds.ccg.data.stats19.data.id.STATS19_RecordID;

public class STATS19_CASUALTY_Record extends Data_Record {

    private static final long serialVersionUID = 1L;

    protected String tAcc_Index;
    protected Byte tVehicle_Reference;
    protected Byte tCasualty_Reference;
    protected Byte tCasualty_Class;
    protected Byte tSex_of_Casualty;
    protected Byte tAge_Band_of_Casualty;
    protected Byte tCasualty_Severity;
    protected Byte tPedestrian_Location;
    protected Byte tPedestrian_Movement;
    protected Byte tCar_Passenger;
    protected Byte tBus_or_Coach_Passenger;
    protected Byte tPedestrian_Road_Maintenance_Worker;
    protected Byte tCasualty_Type;
    protected Byte tCasualty_Home_Area_Type;

    public STATS19_CASUALTY_Record(STATS19_RecordID i, String line) throws Exception {
        super(i);
        String[] s = line.split(",");
        inittAcc_Index(s[0]);
        inittVehicle_Reference(s[1]);
        inittCasualty_Reference(s[2]);
        inittCasualty_Class(s[3]);
        inittSex_of_Casualty(s[4]);
        inittAge_Band_of_Casualty(s[5]);
        inittCasualty_Severity(s[6]);
        inittPedestrian_Location(s[7]);
        inittPedestrian_Movement(s[8]);
        inittCar_Passenger(s[9]);
        inittBus_or_Coach_Passenger(s[10]);
        inittPedestrian_Road_Maintenance_Worker(s[11]);
        inittCasualty_Type(s[12]);
        inittCasualty_Home_Area_Type(s[13]);
    }

    @Override
    public STATS19_RecordID getID() {
        return (STATS19_RecordID) id;
    }

    protected final void inittAcc_Index(String s) {
        if (!s.trim().isEmpty()) {
            tAcc_Index = s;
        } else {
            tAcc_Index = null;
        }
    }

    protected final void inittVehicle_Reference(String s) {
        if (!s.trim().isEmpty()) {
            tVehicle_Reference = Byte.parseByte(s);
        } else {
            tVehicle_Reference = null;
        }
    }

    protected final void inittCasualty_Reference(String s) {
        if (!s.trim().isEmpty()) {
            tCasualty_Reference = Byte.parseByte(s);
        } else {
            tCasualty_Reference = null;
        }
    }

    protected final void inittCasualty_Class(String s) {
        if (!s.trim().isEmpty()) {
            tCasualty_Class = Byte.parseByte(s);
        } else {
            tCasualty_Class = null;
        }
    }

    protected final void inittSex_of_Casualty(String s) {
        if (!s.trim().isEmpty()) {
            tSex_of_Casualty = Byte.parseByte(s);
        } else {
            tSex_of_Casualty = null;
        }
    }

    protected final void inittAge_Band_of_Casualty(String s) {
        if (!s.trim().isEmpty()) {
            tAge_Band_of_Casualty = Byte.parseByte(s);
        } else {
            tAge_Band_of_Casualty = null;
        }
    }

    protected final void inittCasualty_Severity(String s) {
        if (!s.trim().isEmpty()) {
            tCasualty_Severity = Byte.parseByte(s);
        } else {
            tCasualty_Severity = null;
        }
    }

    protected final void inittPedestrian_Location(String s) {
        if (!s.trim().isEmpty()) {
            tPedestrian_Location = Byte.parseByte(s);
        } else {
            tPedestrian_Location = null;
        }
    }

    protected final void inittPedestrian_Movement(String s) {
        if (!s.trim().isEmpty()) {
            tPedestrian_Movement = Byte.parseByte(s);
        } else {
            tPedestrian_Movement = null;
        }
    }

    protected final void inittCar_Passenger(String s) {
        if (!s.trim().isEmpty()) {
            tCar_Passenger = Byte.parseByte(s);
        } else {
            tCar_Passenger = null;
        }
    }

    protected final void inittBus_or_Coach_Passenger(String s) {
        if (!s.trim().isEmpty()) {
            tBus_or_Coach_Passenger = Byte.parseByte(s);
        } else {
            tBus_or_Coach_Passenger = null;
        }
    }

    protected final void inittPedestrian_Road_Maintenance_Worker(String s) {
        if (!s.trim().isEmpty()) {
            tPedestrian_Road_Maintenance_Worker = Byte.parseByte(s);
        } else {
            tPedestrian_Road_Maintenance_Worker = null;
        }
    }

    protected final void inittCasualty_Type(String s) {
        if (!s.trim().isEmpty()) {
            tCasualty_Type = Byte.parseByte(s);
        } else {
            tCasualty_Type = null;
        }
    }

    protected final void inittCasualty_Home_Area_Type(String s) {
        if (!s.trim().isEmpty()) {
            tCasualty_Home_Area_Type = Byte.parseByte(s);
        } else {
            tCasualty_Home_Area_Type = null;
        }
    }

    public String gettAcc_Index() {
        return tAcc_Index;
    }

    public Byte gettVehicle_Reference() {
        return tVehicle_Reference;
    }

    public Byte gettCasualty_Reference() {
        return tCasualty_Reference;
    }

    public Byte gettCasualty_Class() {
        return tCasualty_Class;
    }

    public Byte gettSex_of_Casualty() {
        return tSex_of_Casualty;
    }

    public Byte gettAge_Band_of_Casualty() {
        return tAge_Band_of_Casualty;
    }

    public Byte gettCasualty_Severity() {
        return tCasualty_Severity;
    }

    public Byte gettPedestrian_Location() {
        return tPedestrian_Location;
    }

    public Byte gettPedestrian_Movement() {
        return tPedestrian_Movement;
    }

    public Byte gettCar_Passenger() {
        return tCar_Passenger;
    }

    public Byte gettBus_or_Coach_Passenger() {
        return tBus_or_Coach_Passenger;
    }

    public Byte gettPedestrian_Road_Maintenance_Worker() {
        return tPedestrian_Road_Maintenance_Worker;
    }

    public Byte gettCasualty_Type() {
        return tCasualty_Type;
    }

    public Byte gettCasualty_Home_Area_Type() {
        return tCasualty_Home_Area_Type;
    }
}
